export const CATEGORY_THRESHOLDS: Record<string, number> = {
  clickbait: 0.35,
  toxic: 0.33,
  dark_pattern: 0.32,
  fear: 0.33,
  scam: 0.33,
  adult_content: 0.34,
};

export const MARGIN = 0.05;

export const POSITIVE_ARCHETYPES: Record<string, string[]> = {
  clickbait: [
    "You won't believe what happens next!",
    "7 secrets they don't want you to know",
    "Is this the end for everything?",
    "This one trick will change your life forever",
    "Watch before it gets deleted!",
    "I can't believe this actually worked",
    "Nobody expected this to happen",
    "The results will shock you",
    "What they're hiding from you",
    "You NEED to see this right now",
    "Everyone was wrong about this",
    "This changes everything you thought you knew",
    "I tried this and was completely shocked",
    "The truth finally revealed",
  ],
  toxic: [
    "Haha, you guys are a bunch of losers",
    "Go back to where you came from",
    "I'm going to find you and make you pay",
    "Celebrity completely destroyed in heated argument",
    "Gets absolutely humiliated on live TV",
    "EXPOSED as a fraud and total liar",
    "Savage takedown brutal response gets owned",
    "Public meltdown breakdown caught on camera",
    "Tears apart opponent's credibility",
    "The complete downfall and cancellation",
    "Claps back at haters and trolls",
    "Fires back with devastating comeback",
  ],
  dark_pattern: [
    "Only 2 items left at this price!",
    "Hurry, offer expires in 10 minutes!",
    "Join 50,000 others who already bought this",
    "Watch NOW before this gets taken down",
    "URGENT you need to act immediately",
    "Last chance you'll ever have to see this",
    "They're deleting this video tomorrow",
    "Like and subscribe or bad things will happen",
    "Only 1% of people can solve this",
    "Bet you can't watch without reacting",
    "Share with friends or you'll miss out forever",
    "Time is running out act fast now",
  ],
  fear: [
    "Economic collapse is coming prepare yourself now",
    "We're all doomed and here's the proof",
    "Get out while you still can",
    "The crisis nobody saw coming",
    "Point of no return for humanity",
    "Everything is about to change drastically",
    "Terrifying new threat nobody talks about",
    "Why everyone should be worried right now",
    "The world as we know it is ending",
    "Prepare for the worst case scenario",
  ],
  scam: [
    "Make thousands of dollars per day easy money",
    "Secret passive income method nobody knows",
    "Quit your job get rich quick with this trick",
    "Free money hack that actually works guaranteed",
    "Millionaire reveals secret wealth building method",
    "This one investment will make you rich overnight",
    "I made ten thousand dollars doing nothing",
    "Work from home earn six figures easily",
    "Financial freedom overnight no experience needed",
  ],
  adult_content: [
    "Brutal street fight caught on camera graphic violence",
    "Scary horror movie moments that will traumatize you",
    "True crime serial killer documentary disturbing details",
    "Getting blackout drunk challenge gone wrong",
    "Drug trip experience what it's really like",
    "Sexy bikini haul try on 18+ only",
    "Creepypasta horror story that will give you nightmares",
    "Real ghost sightings terrifying paranormal activity",
    "Gambling all my money at the casino betting big",
    "Extreme gore and violence compilation not for kids",
    "Prank gone sexual in public gone wrong",
    "Drunk party fails people getting wasted",
  ],
};

export const NEGATIVE_ARCHETYPES: string[] = [
  "A comprehensive tutorial on web development",
  "How to learn programming step by step",
  "History documentary about ancient civilizations",
  "Scientific explanation of how the universe works",
  "Cooking recipe: how to make pasta from scratch",
  "Product review with honest pros and cons",
  "Educational lecture on economics and markets",
  "News analysis with multiple perspectives",
  "Music performance live concert recording",
  "Travel vlog visiting historical landmarks",
  "The 7 scariest dark patterns in e-commerce explained",
  "What is clickbait and how to recognize it",
  "Understanding toxic behavior in online communities",
  "How scams work and how to protect yourself",
  "Financial literacy basics for beginners",
  "Psychology of fear and how media uses it",
  "Critical thinking skills for evaluating content",
  "Documentary about the history of advertising",
  "Interview with an expert on social media",
  "Book review and discussion of key themes",
  "Workout routine for beginners at home",
  "DIY home improvement project walkthrough",
  "Software engineering best practices explained",
  "Math tutorial solving equations step by step",
];
